"""allow staff without a provisioned login

Revision ID: 987c7948005f
Revises: f5141eb4a915
Create Date: 2026-08-11 11:45:19.034151

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "987c7948005f"
down_revision: str | None = "f5141eb4a915"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("staff", "auth_user_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("staff", "auth_user_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
