"""initial schema

Revision ID: f5141eb4a915
Revises:
Create Date: 2026-08-11 10:47:39.094114

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "f5141eb4a915"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Tables to enable RLS on. See docs/schema.md.
_APPLICATION_TABLES = (
    "appointment_slots",
    "appointments",
    "audit_log",
    "availability_rules",
    "blocked_ranges",
    "cine_clips",
    "cine_frames",
    "identity_attempts",
    "identity_verifications",
    "images",
    "patients",
    "providers",
    "reminder_sends",
    "reports",
    "share_links",
    "staff",
    "studies",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "actor_type",
            sa.Enum("patient", "staff", "share_link", "system", name="audit_actor_type"),
            nullable=False,
        ),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("resource_type", sa.Text(), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_actor_type_actor_id_occurred_at",
        "audit_log",
        ["actor_type", "actor_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_resource_type_resource_id",
        "audit_log",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_table(
        "identity_attempts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("auth_user_id", sa.UUID(), nullable=False),
        sa.Column("submitted_account_id", sa.Text(), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_attempts")),
    )
    op.create_index(
        "ix_identity_attempts_auth_user_id_created_at",
        "identity_attempts",
        ["auth_user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "patients",
        sa.Column("account_id", sa.Text(), nullable=False),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column("first_name", sa.Text(), nullable=False),
        sa.Column("last_name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("auth_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patients")),
        sa.UniqueConstraint("account_id", name=op.f("uq_patients_account_id")),
        sa.UniqueConstraint("auth_user_id", name=op.f("uq_patients_auth_user_id")),
    )
    op.create_table(
        "providers",
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("specialty", sa.Text(), nullable=True),
        sa.Column("timezone", sa.Text(), server_default="America/New_York", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_providers")),
    )
    op.create_table(
        "appointment_slots",
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "blocked", name="slot_status"),
            server_default="open",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_utc > start_utc",
            name=op.f("ck_appointment_slots_appointment_slots_end_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_appointment_slots_provider_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointment_slots")),
        sa.UniqueConstraint(
            "provider_id", "start_utc", name="uq_appointment_slots_provider_id_start_utc"
        ),
    )
    op.create_index(
        "ix_appointment_slots_provider_id_start_utc_open",
        "appointment_slots",
        ["provider_id", "start_utc"],
        unique=False,
        postgresql_where=sa.text("status = 'open'"),
    )
    op.create_table(
        "availability_rules",
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("start_local", sa.Time(), nullable=False),
        sa.Column("end_local", sa.Time(), nullable=False),
        sa.Column("slot_minutes", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_local > start_local",
            name=op.f("ck_availability_rules_availability_rules_end_after_start"),
        ),
        sa.CheckConstraint(
            "slot_minutes BETWEEN 5 AND 240",
            name=op.f("ck_availability_rules_availability_rules_slot_minutes_sane"),
        ),
        sa.CheckConstraint(
            "weekday BETWEEN 1 AND 7",
            name=op.f("ck_availability_rules_availability_rules_weekday_iso"),
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_availability_rules_provider_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_availability_rules")),
    )
    op.create_index(
        "ix_availability_rules_provider_id", "availability_rules", ["provider_id"], unique=False
    )
    op.create_table(
        "blocked_ranges",
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("start_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_utc", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_utc > start_utc", name=op.f("ck_blocked_ranges_blocked_ranges_end_after_start")
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_blocked_ranges_provider_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_blocked_ranges")),
    )
    op.create_index(
        "ix_blocked_ranges_provider_id_start_utc",
        "blocked_ranges",
        ["provider_id", "start_utc"],
        unique=False,
    )
    op.create_table(
        "identity_verifications",
        sa.Column("auth_user_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_identity_verifications_patient_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identity_verifications")),
    )
    op.create_index(
        "ix_identity_verifications_auth_user_id_expires_at",
        "identity_verifications",
        ["auth_user_id", "expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_identity_verifications_patient_id",
        "identity_verifications",
        ["patient_id"],
        unique=False,
    )
    op.create_table(
        "share_links",
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column(
            "resource_type", sa.Enum("image", "report", name="share_resource_type"), nullable=False
        ),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("created_by_patient_id", sa.UUID(), nullable=False),
        sa.Column("recipient_email", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_patient_id"],
            ["patients.id"],
            name=op.f("fk_share_links_created_by_patient_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_share_links")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_share_links_token_hash")),
    )
    op.create_index(
        "ix_share_links_created_by_patient_id",
        "share_links",
        ["created_by_patient_id"],
        unique=False,
    )
    op.create_index(
        "ix_share_links_resource_type_resource_id",
        "share_links",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_table(
        "staff",
        sa.Column("auth_user_id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Enum("provider", "admin", name="staff_role"), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["providers.id"], name=op.f("fk_staff_provider_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_staff")),
        sa.UniqueConstraint("auth_user_id", name=op.f("uq_staff_auth_user_id")),
    )
    op.create_index("ix_staff_provider_id", "staff", ["provider_id"], unique=False)
    op.create_table(
        "studies",
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column("provider_id", sa.UUID(), nullable=True),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("scheduled", "in_progress", "completed", "cancelled", name="study_status"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_studies_patient_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["providers.id"],
            name=op.f("fk_studies_provider_id"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_studies")),
    )
    op.create_index(
        "ix_studies_patient_id_performed_at_completed",
        "studies",
        ["patient_id", "performed_at"],
        unique=False,
        postgresql_where=sa.text("status = 'completed'"),
    )
    op.create_index("ix_studies_provider_id", "studies", ["provider_id"], unique=False)
    op.create_table(
        "appointments",
        sa.Column("slot_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "requested",
                "confirmed",
                "completed",
                "cancelled",
                "no_show",
                name="appointment_status",
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("booked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'cancelled') = (cancelled_at IS NOT NULL)",
            name=op.f("ck_appointments_appointments_cancelled_state_consistent"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
            name=op.f("fk_appointments_patient_id"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["slot_id"],
            ["appointment_slots.id"],
            name=op.f("fk_appointments_slot_id"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_appointments")),
    )
    op.create_index("ix_appointments_patient_id", "appointments", ["patient_id"], unique=False)
    op.create_index(
        "uq_appointments_idempotency_key",
        "appointments",
        ["idempotency_key"],
        unique=True,
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.create_index(
        "uq_appointments_slot_id_live",
        "appointments",
        ["slot_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('requested', 'confirmed')"),
    )
    op.create_table(
        "cine_clips",
        sa.Column("study_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("frame_count", sa.Integer(), nullable=False),
        sa.Column("default_fps", sa.Integer(), server_default="12", nullable=False),
        sa.Column("manifest_path", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "default_fps BETWEEN 1 AND 60",
            name=op.f("ck_cine_clips_cine_clips_default_fps_playable"),
        ),
        sa.CheckConstraint(
            "frame_count BETWEEN 1 AND 100",
            name=op.f("ck_cine_clips_cine_clips_frame_count_within_limit"),
        ),
        sa.ForeignKeyConstraint(
            ["study_id"], ["studies.id"], name=op.f("fk_cine_clips_study_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cine_clips")),
        sa.UniqueConstraint("study_id", "sequence", name="uq_cine_clips_study_id_sequence"),
    )
    op.create_table(
        "images",
        sa.Column("study_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("thumbnail_path", sa.Text(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("byte_size >= 0", name=op.f("ck_images_images_non_negative_size")),
        sa.CheckConstraint(
            "width > 0 AND height > 0", name=op.f("ck_images_images_positive_dimensions")
        ),
        sa.ForeignKeyConstraint(
            ["study_id"], ["studies.id"], name=op.f("fk_images_study_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_images")),
        sa.UniqueConstraint("study_id", "sequence", name="uq_images_study_id_sequence"),
    )
    op.create_table(
        "reports",
        sa.Column("study_id", sa.UUID(), nullable=False),
        sa.Column("patient_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("preliminary", "final", "amended", name="report_status"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signed_by_provider_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'preliminary' AND signed_at IS NULL)"
            " OR (status IN ('final', 'amended') AND signed_at IS NOT NULL)",
            name=op.f("ck_reports_reports_signed_state_consistent"),
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"], ["patients.id"], name=op.f("fk_reports_patient_id"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["signed_by_provider_id"],
            ["providers.id"],
            name=op.f("fk_reports_signed_by_provider_id"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["study_id"], ["studies.id"], name=op.f("fk_reports_study_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(
        "ix_reports_patient_id_signed",
        "reports",
        ["patient_id"],
        unique=False,
        postgresql_where=sa.text("status IN ('final', 'amended')"),
    )
    op.create_index(
        "ix_reports_signed_by_provider_id", "reports", ["signed_by_provider_id"], unique=False
    )
    op.create_index("ix_reports_study_id", "reports", ["study_id"], unique=False)
    op.create_table(
        "cine_frames",
        sa.Column("clip_id", sa.UUID(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("storage_path", sa.Text(), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column(
            "integrity",
            sa.Enum("ok", "missing", "corrupt", name="frame_integrity"),
            server_default="ok",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sequence BETWEEN 0 AND 99",
            name=op.f("ck_cine_frames_cine_frames_sequence_within_limit"),
        ),
        sa.ForeignKeyConstraint(
            ["clip_id"], ["cine_clips.id"], name=op.f("fk_cine_frames_clip_id"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cine_frames")),
        sa.UniqueConstraint("clip_id", "sequence", name="uq_cine_frames_clip_id_sequence"),
    )
    op.create_table(
        "reminder_sends",
        sa.Column("appointment_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Enum("pre_visit_24h", name="reminder_kind"), nullable=False),
        sa.Column("status", sa.Enum("sent", "failed", name="reminder_status"), nullable=False),
        sa.Column("attempted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("provider_message_id", sa.Text(), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
            name=op.f("fk_reminder_sends_appointment_id"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reminder_sends")),
        sa.UniqueConstraint("appointment_id", "kind", name="uq_reminder_sends_appointment_id_kind"),
    )
    # ### end Alembic commands ###

    # Append-only enforced in the database, not by convention.
    op.execute(
        """
        CREATE FUNCTION audit_log_reject_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only: % is not permitted', TG_OP;
        END;
        $$;
        """
    )
    op.execute(
        """
        CREATE TRIGGER audit_log_append_only
        BEFORE UPDATE OR DELETE ON audit_log
        FOR EACH ROW EXECUTE FUNCTION audit_log_reject_mutation();
        """
    )

    # RLS with no policies blocks Supabase's PostgREST endpoint, which would otherwise
    # serve these tables to the browser's publishable key. Not FORCEd: that would lock out
    # the API too. See docs/schema.md.
    for table_name in _APPLICATION_TABLES:
        op.execute(f"ALTER TABLE public.{table_name} ENABLE ROW LEVEL SECURITY")


def downgrade() -> None:
    for table_name in _APPLICATION_TABLES:
        op.execute(f"ALTER TABLE IF EXISTS public.{table_name} DISABLE ROW LEVEL SECURITY")

    op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_reject_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reminder_sends")
    op.drop_table("cine_frames")
    op.drop_index("ix_reports_study_id", table_name="reports")
    op.drop_index("ix_reports_signed_by_provider_id", table_name="reports")
    op.drop_index(
        "ix_reports_patient_id_signed",
        table_name="reports",
        postgresql_where=sa.text("status IN ('final', 'amended')"),
    )
    op.drop_table("reports")
    op.drop_table("images")
    op.drop_table("cine_clips")
    op.drop_index(
        "uq_appointments_slot_id_live",
        table_name="appointments",
        postgresql_where=sa.text("status IN ('requested', 'confirmed')"),
    )
    op.drop_index(
        "uq_appointments_idempotency_key",
        table_name="appointments",
        postgresql_where=sa.text("idempotency_key IS NOT NULL"),
    )
    op.drop_index("ix_appointments_patient_id", table_name="appointments")
    op.drop_table("appointments")
    op.drop_index("ix_studies_provider_id", table_name="studies")
    op.drop_index(
        "ix_studies_patient_id_performed_at_completed",
        table_name="studies",
        postgresql_where=sa.text("status = 'completed'"),
    )
    op.drop_table("studies")
    op.drop_index("ix_staff_provider_id", table_name="staff")
    op.drop_table("staff")
    op.drop_index("ix_share_links_resource_type_resource_id", table_name="share_links")
    op.drop_index("ix_share_links_created_by_patient_id", table_name="share_links")
    op.drop_table("share_links")
    op.drop_index("ix_identity_verifications_patient_id", table_name="identity_verifications")
    op.drop_index(
        "ix_identity_verifications_auth_user_id_expires_at", table_name="identity_verifications"
    )
    op.drop_table("identity_verifications")
    op.drop_index("ix_blocked_ranges_provider_id_start_utc", table_name="blocked_ranges")
    op.drop_table("blocked_ranges")
    op.drop_index("ix_availability_rules_provider_id", table_name="availability_rules")
    op.drop_table("availability_rules")
    op.drop_index(
        "ix_appointment_slots_provider_id_start_utc_open",
        table_name="appointment_slots",
        postgresql_where=sa.text("status = 'open'"),
    )
    op.drop_table("appointment_slots")
    op.drop_table("providers")
    op.drop_table("patients")
    op.drop_index("ix_identity_attempts_auth_user_id_created_at", table_name="identity_attempts")
    op.drop_table("identity_attempts")
    op.drop_index("ix_audit_log_resource_type_resource_id", table_name="audit_log")
    op.drop_index("ix_audit_log_actor_type_actor_id_occurred_at", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###

    # Alembic creates enum types implicitly but never drops them, so without this a
    # downgrade would break the next upgrade with "type already exists".
    for enum_name in (
        "appointment_status",
        "audit_actor_type",
        "frame_integrity",
        "reminder_kind",
        "reminder_status",
        "report_status",
        "share_resource_type",
        "slot_status",
        "staff_role",
        "study_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
